config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :empresas do
    resources :votos
  end

  root 'welcome#index'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :area
  belongs_to :calificacion
  validates_presence_of :empresa_id
  validates_presence_of :email
  validates_presence_of :calificacion_id
  validates_presence_of :area_id
  validates :email, presence: true,  length: { minimum: 5 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  #confirmation: true
  #validates :email_confirmation, presence: true
end

app/controllers/votos_controller.rb
class VotosController < ApplicationController
  before_action :set_voto, only: [:show, :edit, :update, :destroy]

  # GET /votos
  # GET /votos.json
  def index
    @votos = Voto.all
  end

  # GET /votos/1
  # GET /votos/1.json
  def show
  end

  # GET /votos/new
  def new
    @voto = Voto.new
  end

  # GET /votos/1/edit
  def edit
  end

  # POST /votos
  # POST /votos.json
  def create
    @empresa = Empresa.find(params[:empresa_id])
    @voto = @empresa.votos.create(voto_params)

    respond_to do |format|
      if @voto.save
        format.html { redirect_to @empresa, notice: 'Vote was created.' }
        format.json { render :show, status: :created, location: @voto }
      elsif voto_params[:email].empty?
        error = ""
        @voto.errors.full_messages.each do |message|
          error += message
        end
        format.html { redirect_to @empresa, notice: 'Email Incorrecto.'+ params.to_s}
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to @empresa, notice: 'Error. Revise los datos.' + voto_params[:email] }
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /votos/1
  # PATCH/PUT /votos/1.json
  def update
    respond_to do |format|
      if @voto.update(voto_params)
        format.html { redirect_to @voto, notice: 'Voto was successfully updated.' }
        format.json { render :show, status: :ok, location: @voto }
      else
        format.html { render :edit }
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votos/1
  # DELETE /votos/1.json
  def destroy
    @voto.destroy
    respond_to do |format|
      format.html { redirect_to votos_url, notice: 'Voto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voto
      @voto = Voto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voto_params
      params.require(:voto).permit(:email, :area_id, :calificacion_id, :empresa_id)
    end
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/votos/_form.html.erb
<%= form_for([@empresa, Voto.new]) do |f| %>
	<table>
		<% @areas.each do |area| %>
			<tr>
				<td class="hidden"><%= area.id %></td>
	    		<td><%= area.nombre %></td>
	    		<% @calificaciones.each do |calificacion| %>
			    	<td>
				    	<input type="radio" name="Area_<%= area.id %>" id="Id_<%= area.id %>_<%= calificacion.id %>" class="css-checkbox" checked="checked" />
				    	<label for="Id_<%= area.id %>_<%= calificacion.id %>" class="css-label">
				    		<%= image_tag('caritas/negras/' + calificacion.numero.to_s + '.png', height: '40', width: '40') %>
				    	</label>
			    	</td>
			    <% end %>
	    	</tr>
	    <% end %>
	</table>
	<%= f.text_field :email, placeholder: 'Tu Email', :autocomplete => :off %>
    <%= f.submit 'Opinar' %>
    <%= link_to 'Regresar', empresas_path, :class => 'button call_to_action demi-full-width' %>
<% end %>

app/views/votos/edit.html.erb
<h1>Editing voto</h1>

<%= render 'form' %>

<%= link_to 'Show', @voto %> |
<%= link_to 'Back', votos_path %>

app/views/votos/index.html.erb
<h1>Listing votos</h1>

<table>
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Email</th>
      <th>Calificacion</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votos.each do |voto| %>
      <tr>
        <td><%= voto.empresa_id %></td>
        <td><%= voto.email %></td>
        <td><%= voto.calificacion_id %></td>
        <td><%= voto.area_id %></td>
        <td><%= link_to 'Show', voto %></td>
        <td><%= link_to 'Edit', edit_voto_path(voto) %></td>
        <td><%= link_to 'Destroy', voto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voto', new_voto_path %>

app/views/votos/new.html.erb
<h1>New voto</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/votos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @voto.empresa_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @voto.email %>
</p>

<p>
  <strong>Calificacion:</strong>
  <%= @voto.calificacion_id %>
</p>

<p>
  <strong>Area:</strong>
  <%= @voto.area_id %>
</p>

<%= link_to 'Edit', edit_voto_path(@voto) %> |
<%= link_to 'Back', votos_path %>