config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :empresas do
    resources :votos
  end

  root 'welcome#index'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :votos, dependent: :destroy
  validates_presence_of :nombre
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @calificaciones = Calificacion.all
    @areas = Area.all
    @cali = Voto.joins(:area, :calificacion).where(empresa_id: @empresa.id).group("areas.nombre").average("calificacions.numero")
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nombre, :imagen, :visible)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :imagen %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<div class="wrapper">
	<div id="content">
		<div class="row">
			<div class="large-12 small-12">
				<div class="meta_landing">


							<h1>Ranking de Empresas</h1>
							<table>
							  <thead>
							    <tr>
							      <th>Nombre</th>
							      <th>Votos</th>
							    </tr>
							  </thead>

							  <tbody>
							    <% @empresas.each do |empresa| %>
							    	<% if empresa.visible %>
									  <tr>
									    <td>
									    	<% if empresa.imagen.blank? == false %>
									    		<%= link_to image_tag(empresa.imagen, height: '75', width: '75'), empresa, :class => 'th radius' %>
									    	<% else %>
									    		<%= link_to image_tag('blank.png', height: '75', width: '75'), empresa, :class => 'th radius' %>
											<% end %>
									    	<%= link_to empresa.nombre, empresa %>
								    	</td>
									    <td><%= empresa.votos.count %></td>
									    <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
									  </tr>
							    	<% end %>
							    <% end %>
							  </tbody>
							</table>
							<%= link_to 'Nueva Empresa', new_empresa_path, :class => 'button call_to_action demi-full-width' %>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<div class="wrapper">
	<div id="content">
		<div class="row">
			<div class="meta_landing">
				<p id="notice"><%= notice %></p>
				<h1>
					<%= @empresa.nombre %>

				  	<% if @empresa.imagen.blank? == false %>
						<%= image_tag(@empresa.imagen, height: '125', width: '125') %>
					<% else %>
						<%= image_tag('blank.png', height: '125', width: '125', :class => 'th radius') %>
					<% end %>
				</h1>

				<h2>
				  Total Opiniones
				</h2>
				<h3>
				  <%= @empresa.votos.count %>
				</h3>
			</div>
			<hr>
			<div class="row">
				<div class="feature large-5 small-12 columns">
					<h2>
						Opiniones Actuales
					</h2>
					<p>
						Resultado de las opiniones para la empresa.
					</p>
					<table>
						<% @cali.each do |c| %>
							<tr>
					    		<td><%= c[0] %></td>
					    		<td><%= c[1].to_i %></td>
						    	<td>
							    	<%= image_tag('caritas/negras/' + c[1].to_i.to_s + '.png', height: '40', width: '40') %>
						    	</td>
					    	</tr>
					    <% end %>
					</table>
				</div>
				<div class="feature large-7 small-12 columns">
					<h2>
						Ayudanos con tu opinion
					</h2>
					<p>
						Selecciona la opinion que se acerque mas
						a como te sentiste en la empresa, en cada
						una de las areas a calificar.
					</p>
					<%= render "votos/form" %>
				</div>
			</div>
		</div>
	</div>
</div>